import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Toaster } from "sonner";
import Footer from "@/components/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b border-border bg-card">
          <div className=" mx-auto py-3 px-2">
            <div className="flex flex-col items-start justify-between sm:flex-row sm:items-center">
              <Link href="/" className="flex flex-row items-center text-base font-semibold text-foreground sm:text-lg">
               <img
               src="/logo.jpg"
               alt="Carepair Logo"
               className="h-12 w-auto"
               />
                Car Service Dashboard
              </Link>
              <nav className="flex w-full flex-wrap items-center gap-2 sm:w-auto justify-end">
                <Button asChild variant="ghost" size="sm" className="text-neutral-600 justify-start sm:justify-center">
                  <Link href="/">Tickets</Link>
                </Button>
                <Button asChild variant="ghost" size="sm" className="text-neutral-600 justify-start sm:justify-center">
                  <Link href="/appointments">Appointments</Link>
                </Button>
              </nav>
            </div>
          </div>
        </header>
        <main className="w-full pb-12">{children}

        </main>
<Footer/>

        <Toaster position="bottom-right" richColors />
      </body>
    </html>
  );
}
